apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
  namespace: media
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicates: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: prowlarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pv-claim
  namespace: media
spec:
  storageClassName: longhorn
  volumeName: prowlarr-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: prowlarr
      tier: media
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
        tier: media
    spec:
      containers:
      - image: lscr.io/linuxserver/prowlarr:latest
        name: prowlarr
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Americas\New_York
        ports:
        - containerPort: 9696
          name: prowlarr
        volumeMounts:
        - name: prowlarr-persistent-storage
          mountPath: /config
        imagePullPolicy: Always
      volumes:
      - name: prowlarr-persistent-storage
        persistentVolumeClaim:
          claimName: prowlarr-pv-claim
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: media
spec:
  ingressClassName: nginx
  rules:
  - host: prowlarr2.dyslexicjedi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    kubernetes.io/name: "prowlarr"
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
  - name: prowlarr
    port: 80
    targetPort: 9696